baseURL = "http://example.org/"
languageCode = "en-us"
title = "Aang Morningstar"
theme = "aang-theme"
[params]
    Description ="Belajar Hugo"

# [permalinks]
#     blog = ":title" #ahmadmuzaki.com/blog/ahmadmuzaki menjadi ahmadmuzaki.com/ahmadmuzaki