baseURL = "http://localhost/"
languageCode = "en-us"
title = "Aang Morningstar"
theme = "aang-theme"

# [permalinks]
#     blog = ":title" #ahmadmuzaki.com/blog/ahmadmuzaki menjadi ahmadmuzaki.com/ahmadmuzaki